#!/bin/bash
#
# Running on a gds/puppet managed install of mapit
#
# Matthew Somerville <matthew@mysociety.org>

set -e

source ./find-mapit-venv

export MANAGE="/usr/local/bin/govuk_setenv mapit $MAPIT_VENV_DIR/bin/python /var/apps/mapit/manage.py"

# Okay, let's start the import. Instructions taken from
# http://code.mapit.mysociety.org/import/uk/

$MANAGE mapit_generation_create --commit --desc "Initial import of BL 2016-05, ONSPD 2016-05, and OSNI 2015-12"
$MANAGE loaddata uk

# Boundary-Line
echo "Fetching Boundary-Line from mySociety cache"
if [ ! -e bdline_gb-2016-05.zip ]; then
    curl -O http://parlvid.mysociety.org/os/bdline_gb-2016-05.zip
fi
mkdir -p Boundary-Line
unzip -d Boundary-Line -o bdline_gb-2016-05.zip

echo "Importing Boundary-Line"
$MANAGE mapit_UK_import_boundary_line --control=mapit_gb.controls.first-gss --commit `ls Boundary-Line/Data/**/*.shp|grep -Ev high_water\|parish_region\|Supplementary_\[Historical\|Ceremonial\]\|Wales/community_ward_region`

echo "Importing OSNI"
source ./check-osni-downloads
osni_import_arguments=""
for osni_type in "${!osni_types[@]}"
do
  suffix=${osni_types["$osni_type"]}
  file="$osni_folder/$osni_prefix$suffix/$osni_prefix$suffix.shp"
  srid=`cat $osni_folder/metadata.json | ruby -e "require 'json'; begin; puts JSON.parse(STDIN.read).fetch('$osni_prefix$suffix',{}).fetch('srid'); rescue; end"`
  osni_import_arguments="$osni_import_arguments --$osni_type=$file"
  if [[ $srid ]]; then
    osni_import_arguments="$osni_import_arguments --$osni_type-srid=$srid"
  fi
done
$MANAGE mapit_UK_import_osni --control=mapit_gb.controls.first-gss $osni_import_arguments --commit

echo "Associating boundary shapes with their parents (this is generational and can take up to 10 minutes)"
$MANAGE mapit_UK_find_parents --commit

echo "Adding names from legislation to OSNI imported areas"
$MANAGE mapit_UK_add_names_to_ni_areas

echo "Fetching ONSPD from the MySociety cache"
if [ ! -e ONSPD_MAY_2016_csv.zip ]; then
    curl -O http://parlvid.mysociety.org/os/ONSPD_MAY_2016_csv.zip
fi
unzip -d ONSPD -o ONSPD_MAY_2016_csv.zip

echo "Importing All GB Postcodes (live, terminated, and those with no location from GB, NI, and Crown Dependencies) from ONSPD"
$MANAGE mapit_UK_import_onspd --allow-terminated-postcodes --allow-no-location-postcodes --crown-dependencies=include --northern-ireland=include ONSPD/Data/ONSPD_MAY_2016_UK.csv

echo "Dealing with Isles of Scilly and special postcodes"
$MANAGE mapit_UK_scilly --allow-no-location-postcodes --allow-terminated-postcodes ONSPD/Data/ONSPD_MAY_2016_UK.csv
$MANAGE loaddata uk_special_postcodes

echo "Adding some missing GSS and ONS Codes"
$MANAGE mapit_UK_add_missing_codes
$MANAGE mapit_UK_add_ons_to_gss

echo "Assigning govuk slugs to councils"
$MANAGE mapit_UK_add_slugs_to_local_authorities

echo "Activate"
$MANAGE mapit_generation_activate --commit

echo "Show missing codes"
$MANAGE mapit_UK_show_missing_codes
