#!/bin/bash
#
# Running on a gds/puppet managed install of mapit
#
# Matthew Somerville <matthew@mysociety.org>

set -e

source ./find-mapit-venv

export MANAGE="/usr/local/bin/govuk_setenv mapit $MAPIT_VENV_DIR/bin/python /var/apps/mapit/manage.py"

source ./check-osni-downloads

# Okay, let's start the import. Instructions taken from
# http://code.mapit.mysociety.org/import/uk/

$MANAGE mapit_generation_create --commit --desc "Initial import of BL 2015-10, ONSPD 2015-08, and OSNI 2015-11"
$MANAGE loaddata uk

# Boundary-Line
echo "Fetching Boundary-Line from mySociety cache"
if [ ! -e bdline_gb-2015-10.zip ]; then
    curl -O http://parlvid.mysociety.org/os/bdline_gb-2015-10.zip
fi
mkdir -p Boundary-Line
unzip -d Boundary-Line bdline_gb-2015-10.zip

echo "Importing Boundary-Line"
$MANAGE mapit_UK_import_boundary_line --control=mapit_gb.controls.first-gss --commit `ls Boundary-Line/Data/**/*.shp|grep -Ev high_water\|parish_region\|Supplementary_\[Historical\|Ceremonial\]\|Wales/community_ward_region`

echo "Importing OSNI"
osni_import_arguments=""
for osni_type in "${!osni_types[@]}"
do
  suffix=${osni_types["$osni_type"]}
  file="$osni_folder/$osni_prefix$suffix/$osni_prefix$suffix.shp"
  osni_import_arguments="$osni_import_arguments --$osni_type=$file"
done
$MANAGE mapit_UK_import_osni --control=mapit_gb.controls.first-gss $osni_import_arguments --commit

echo "Associating boundary shapes with their parents (this is generational and can take up to 10 minutes)"
$MANAGE mapit_UK_find_parents --commit

echo "Fetching ONSPD from directly from ONS"
if [ ! -e ONSPD_AUG_2015_csv.zip ]; then
    curl -O https://geoportal.statistics.gov.uk/Docs/PostCodes/ONSPD_AUG_2015_csv.zip
fi
unzip -d ONSPD ONSPD_AUG_2015_csv.zip

echo "Importing All GB Postcodes (live, terminated, and those with no location from GB, NI, and Crown Dependencies) from ONSPD"
$MANAGE mapit_UK_import_onspd --allow-terminated-postcodes --allow-no-location-postcodes --crown-dependencies=include --northern-ireland=include ONSPD/Data/ONSPD_AUG_2015_UK.csv

echo "Dealing with Isles of Scilly and special postcodes"
$MANAGE mapit_UK_scilly --allow-no-location-postcodes --allow-terminated-postcodes ONSPD/Data/ONSPD_AUG_2015_UK.csv
$MANAGE loaddata uk_special_postcodes

echo "Adding some missing GSS and ONS Codes"
$MANAGE mapit_UK_add_missing_codes
$MANAGE mapit_UK_add_ons_to_gss

echo "Activate"
$MANAGE mapit_generation_activate --commit
