#!/bin/bash
#
# Running on a gds/puppet managed install of mapit
#
# Matthew Somerville <matthew@mysociety.org>

set -e

export MANAGE="govuk_setenv mapit /var/apps/mapit/.venv/bin/python /var/apps/mapit/manage.py"

# Okay, let's start the import. Instructions taken from
# http://code.mapit.mysociety.org/import/uk/

$MANAGE mapit_generation_create --commit --desc "Initial import of BL 2015-10 and merged Code-Point up to 2015-05."
$MANAGE loaddata uk

# Boundary-Line
echo "Fetching Boundary-Line from mySociety cache"
if [ ! -e bdline_gb-2015-10.zip ]; then
    curl -O http://parlvid.mysociety.org/os/bdline_gb-2015-10.zip
fi
mkdir -p Boundary-Line
unzip -d Boundary-Line bdline_gb-2015-10.zip

echo "Importing Boundary-Line"
$MANAGE mapit_UK_import_boundary_line --control=mapit_gb.controls.first-gss --commit `ls Boundary-Line/Data/**/*.shp|grep -Ev high_water\|parish_region\|Supplementary_\[Historical\|Ceremonial\]\|Wales/community_ward_region`
echo "Associating boundary shapes with their parents (this is generational and can take up to 10 minutes)"
$MANAGE mapit_UK_find_parents --commit

# If you want to just load latest codepoint, then download it and run
# if [ ! -e codepo_gb-2015-05.zip ]; then
#     curl -O http://parlvid.mysociety.org:81/os/codepo_gb-2015-05.zip
# fi
# mkdir -p Code-Point
# unzip -d Code-Point codepo_gb-2015-05.zip
# sudo -u mapit $MANAGE mapit_UK_import_codepoint Code-Point/Data/*.csv

echo "Fetching Code-Points"
./get-all-codepoints
./merge-all-codepoints

echo "Importing Code-Points"
$MANAGE mapit_UK_import_codepoint merged/*.csv

echo "Dealing with Northern Ireland"
if [ ! -e ONSPD_NOV_2014_csv.zip ]; then
    curl -O http://parlvid.mysociety.org/os/ONSPD_NOV_2014_csv.zip
fi
mkdir -p ONSPD
unzip -d ONSPD ONSPD_NOV_2014_csv.zip

$MANAGE mapit_UK_import_nspd_ni_areas
$MANAGE mapit_UK_import_nspd_ni ONSPD/Data/ONSPD_NOV_2014_UK.csv
$MANAGE mapit_UK_import_nspd_crown_dependencies ONSPD/Data/ONSPD_NOV_2014_UK.csv

echo "Dealing with Isles of Scilly and special postcodes"
$MANAGE mapit_UK_scilly merged/tr.csv
$MANAGE loaddata uk_special_postcodes

echo "Activate"
$MANAGE mapit_generation_activate --commit

echo "Oh, and add the old ONS codes as a bonus"
$MANAGE mapit_UK_add_ons_to_gss
